/** All visual and numeric lab outputs use these pure, tested functions. */
export const clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
export function rng(seed=1){let s=(Number(seed)>>>0)||1;return()=>{s=(s+0x6D2B79F5)>>>0;let t=Math.imul(s^(s>>>15),1|s);t^=t+Math.imul(t^(t>>>7),61|t);return((t^(t>>>14))>>>0)/4294967296;};}
export function normal(random){return Math.sqrt(-2*Math.log(Math.max(random(),1e-12)))*Math.cos(2*Math.PI*random());}
export const regressionData=[[-2,-3.7],[-1,-1.2],[0,.9],[1,2.8],[2,5.2]];
export function regression(w,b,data=regressionData){const points=data.map(([x,y])=>({x,y,pred:w*x+b,residual:w*x+b-y}));return{points,mse:points.reduce((s,p)=>s+p.residual**2,0)/points.length,gradient:[2*points.reduce((s,p)=>s+p.residual*p.x,0)/points.length,2*points.reduce((s,p)=>s+p.residual,0)/points.length]};}
export function descent(w,b,lr,steps=1,data=regressionData){let path=[{w,b,loss:regression(w,b,data).mse}];for(let i=0;i<steps;i++){const [dw,db]=regression(w,b,data).gradient;w-=lr*dw;b-=lr*db;if(!Number.isFinite(w+b)||Math.abs(w)+Math.abs(b)>1e8)break;path.push({w,b,loss:regression(w,b,data).mse});}return path;}
export function softmax(xs){if(!xs.length||xs.some(x=>!Number.isFinite(x)))throw Error('softmax 输入需要非空有限数');const m=Math.max(...xs),es=xs.map(x=>Math.exp(x-m)),sum=es.reduce((a,b)=>a+b,0);return es.map(x=>x/sum);}
export const dot=(a,b)=>{if(a.length!==b.length||!a.length)throw Error('张量维度不匹配');return a.reduce((s,x,i)=>s+x*b[i],0);};
export function matmul(A,B){if(!A.length||!B.length||!B[0].length||A.some(r=>r.length!==B.length)||B.some(r=>r.length!==B[0].length))throw Error('矩阵维度不匹配');return A.map(row=>B[0].map((_,j)=>dot(row,B.map(r=>r[j]))));}
export function attention(X,scale=true){if(X.length!==3||X.some(r=>r.length!==2||r.some(x=>!Number.isFinite(x))))throw Error('X 必须是 3×2 有限矩阵');const Wq=[[1,0],[0,1]],Wk=[[1,.5],[.5,1]],Wv=[[1,-1],[.5,1]],Q=matmul(X,Wq),K=matmul(X,Wk),V=matmul(X,Wv);const scores=Q.map(q=>K.map(k=>dot(q,k)/(scale?Math.sqrt(2):1))),weights=scores.map(softmax),output=matmul(weights,V);return{X,Wq,Wk,Wv,Q,K,V,scores,weights,output};}
export const image=[[1,2,0,1],[0,1,3,2],[2,1,0,1],[1,0,2,3]];
export const kernels={edge:[[1,0],[-1,0]],average:[[.25,.25],[.25,.25]],diagonal:[[1,0],[0,-1]]};
export function convolution(input,kernel){if(!input.length||!input[0].length||!kernel.length||!kernel[0].length||input.flat().some(x=>!Number.isFinite(x))||kernel.flat().some(x=>!Number.isFinite(x))||input.some(r=>r.length!==input[0].length)||kernel.some(r=>r.length!==kernel[0].length)||input.length<kernel.length||input[0].length<kernel[0].length)throw Error('卷积张量尺寸无效');return Array.from({length:input.length-kernel.length+1},(_,i)=>Array.from({length:input[0].length-kernel[0].length+1},(_,j)=>{const terms=kernel.flatMap((r,u)=>r.map((k,v)=>({input:input[i+u][j+v],kernel:k,product:input[i+u][j+v]*k,row:i+u,col:j+v})));return{terms,value:terms.reduce((s,t)=>s+t.product,0)};}));}
export function makeData(seed=17){const r=rng(seed),train=Array.from({length:24},(_,i)=>{const x=-1+2*i/23;return[x,Math.sin(3*x)+.12*normal(r)];}),validation=Array.from({length:31},(_,i)=>{const x=-.985+1.97*i/30;return[x,Math.sin(3*x)+.12*normal(r)];});return{train,validation};}
const act={tanh:x=>Math.tanh(x),relu:x=>Math.max(0,x),linear:x=>x};
const deriv={tanh:x=>1-Math.tanh(x)**2,relu:x=>x>0?1:0,linear:x=>1};
export function initNN(width=6,activation='tanh',seed=17){if(!['tanh','relu','linear'].includes(activation)||!Number.isInteger(width)||width<1||width>20)throw Error('模型参数无效');const r=rng(seed);return{width,activation,a:Array.from({length:width},()=>normal(r)*.7),b:Array.from({length:width},()=>normal(r)*.15),c:Array.from({length:width},()=>normal(r)*.4/Math.sqrt(width)),d:0,epoch:0,history:[],seed};}
export function predict(model,x){return model.d+model.a.reduce((s,a,j)=>s+model.c[j]*act[model.activation](a*x+model.b[j]),0);}
export function nnLoss(m,data){return data.reduce((s,[x,y])=>s+(predict(m,x)-y)**2,0)/data.length;}
export function nnGrad(m,data){const g={a:Array(m.width).fill(0),b:Array(m.width).fill(0),c:Array(m.width).fill(0),d:0};for(const[x,y]of data){const e=2*(predict(m,x)-y)/data.length;g.d+=e;for(let j=0;j<m.width;j++){const z=m.a[j]*x+m.b[j],h=act[m.activation](z),v=e*m.c[j]*deriv[m.activation](z);g.a[j]+=v*x;g.b[j]+=v;g.c[j]+=e*h;}}return g;}
export function trainNN(m,lr=.03,steps=1){const data=makeData(m.seed);for(let k=0;k<steps;k++){const g=nnGrad(m,data.train);for(const key of['a','b','c'])m[key]=m[key].map((v,j)=>v-lr*g[key][j]);m.d-=lr*g.d;m.epoch++;m.history.push({epoch:m.epoch,train:nnLoss(m,data.train),validation:nnLoss(m,data.validation)});if(m.history.length>3001)m.history.shift();}return m;}
export function alphaBar(k,T=40){return Math.exp(Math.log(.015)*k/T);}
export function forwardDiffusion(seed=42,T=40,count=40){const r=rng(seed),clean=Array.from({length:count},()=> (r()<.5?-2:2)+.35*normal(r)),path=[clean];for(let k=1;k<=T;k++){const alpha=alphaBar(k,T)/alphaBar(k-1,T);path.push(path.at(-1).map(x=>Math.sqrt(alpha)*x+Math.sqrt(1-alpha)*normal(r)));}return{clean,path,T};}
export function posterior(x,k,T=40){if(!Number.isInteger(k)||k<1||k>T)throw Error('反向时间步越界');const ap=alphaBar(k-1,T),ak=alphaBar(k,T),step=ak/ap,vp=ap*.35**2+1-ap,vk=ak*.35**2+1-ak,cov=Math.sqrt(step)*vp,means=[-2,2].map(mu=>Math.sqrt(ap)*mu+cov/vk*(x-Math.sqrt(ak)*mu)),variance=Math.max(0,vp-cov*cov/vk),weights=softmax([-2,2].map(mu=>-((x-Math.sqrt(ak)*mu)**2)/(2*vk)));return{means,variance,weights};}
export function reverseDiffusion(seed=42,T=40,count=40){const f=forwardDiffusion(seed,T,count),r=rng(seed+991),path=[f.path[T]];for(let k=T;k>=1;k--){path.push(path.at(-1).map(x=>{const p=posterior(x,k,T),j=r()<p.weights[0]?0:1;return p.means[j]+Math.sqrt(p.variance)*normal(r);}));}return{path,T};}
export function finiteDifference(f,x,h=1e-5){return(f(x+h)-f(x-h))/(2*h);}
