export const STORAGE='anidoc-learning-v1';
export const defaults=()=>({schema:1,guideSeen:false,done:[],answers:{},predictions:{},labs:{regression:{w:0,b:0},gradient:{w:0,b:0,lr:.2,steps:0},nn:{width:6,activation:'tanh',seed:17,lr:.03,epochs:0},convolution:{input:[[1,2,0,1],[0,1,3,2],[2,1,0,1],[1,0,2,3]],kernel:'edge',row:0,col:0},attention:{X:[[1,0],[0,1],[1,1]],scale:true,row:0},diffusion:{seed:42,mode:'forward',step:0},architecture:{frames:14,height:320,width:512,node:0}}});
function range(x,a,b,int=false){return Number.isFinite(x)&&x>=a&&x<=b&&(!int||Number.isInteger(x));}
export function validateState(s){if(!s||s.schema!==1||typeof s.guideSeen!=='boolean'||!Array.isArray(s.done)||s.done.some(x=>!range(x,1,9,true))||!s.answers||typeof s.answers!=='object'||Array.isArray(s.answers)||!s.predictions||typeof s.predictions!=='object'||Array.isArray(s.predictions))throw Error('记录版本或结构不兼容，请使用本站导出的版本 1 文件');const l=s.labs;if(!l||!l.regression||!l.gradient||!l.nn||!l.convolution||!l.attention||!l.diffusion||!l.architecture)throw Error('缺少实验状态');for(const k of['regression','gradient'])if(!range(l[k].w,-5,5)||!range(l[k].b,-5,5))throw Error('回归起点超出范围');if(!range(l.gradient.lr,.005,.6)||!range(l.gradient.steps,0,120,true))throw Error('梯度状态越界');if(!range(l.nn.width,1,12,true)||!['tanh','relu','linear'].includes(l.nn.activation)||!range(l.nn.seed,1,99999,true)||!range(l.nn.lr,.001,.15)||!range(l.nn.epochs,0,3000,true))throw Error('神经网络状态越界');if(!['edge','average','diagonal'].includes(l.convolution.kernel)||!range(l.convolution.row,0,2,true)||!range(l.convolution.col,0,2,true)||!Array.isArray(l.convolution.input)||l.convolution.input.length!==4||l.convolution.input.some(r=>!Array.isArray(r)||r.length!==4||r.some(x=>!range(x,-9,9))))throw Error('卷积形状或数值无效');if(!Array.isArray(l.attention.X)||l.attention.X.length!==3||l.attention.X.some(r=>!Array.isArray(r)||r.length!==2||r.some(x=>!range(x,-5,5)))||typeof l.attention.scale!=='boolean'||!range(l.attention.row,0,2,true))throw Error('注意力形状或数值无效');if(!range(l.diffusion.seed,1,99999,true)||!['forward','reverse'].includes(l.diffusion.mode)||!range(l.diffusion.step,0,40,true))throw Error('扩散状态越界');if(!range(l.architecture.frames,1,24,true)||![160,320,640].includes(l.architecture.height)||![256,512,1024].includes(l.architecture.width)||!range(l.architecture.node,0,6,true))throw Error('架构演示状态越界');for(const[id,a]of Object.entries(s.answers)){if(!/^(?:[1-9][a-d]|[46789][ef]|9g)$/.test(id)||!a||typeof a.value!=='string'||a.value.length>120||typeof a.correct!=='boolean'||!range(a.attempts,1,100000,true)||!range(a.hint,0,2,true)||typeof a.solution!=='boolean')throw Error('练习记录无效');}for(const[k,v]of Object.entries(s.predictions))if(!/^[1-9]$/.test(k)||typeof v!=='string'||v.length>2000)throw Error('预测记录无效');return s;}
export function loadState(){try{const raw=localStorage.getItem(STORAGE);if(!raw)return{state:defaults(),warning:''};return{state:validateState(JSON.parse(raw)),warning:''};}catch(e){try{const raw=localStorage.getItem(STORAGE);if(raw)localStorage.setItem(STORAGE+'-recovery',raw);}catch{}return{state:defaults(),warning:'旧记录未能读取：'+e.message+'。原始文本已尽可能备份；可在“保存与记录”下载。新操作将使用新的有效状态。'};}}
export function saveState(s){try{validateState(s);localStorage.setItem(STORAGE,JSON.stringify(s));return'';}catch(e){return'本次未保存：'+e.message+'。可先导出记录，避免关闭后丢失。';}}
export function grade(q,value){
  if(q.type==='number'){
    const n=Number(value);
    // Decimal inputs at the inclusive 0.001 boundary can differ by a final
    // binary rounding bit. Allow representation error, not a wider tolerance.
    const roundoff=Number.EPSILON*Math.max(1,Math.abs(n),Math.abs(q.answer));
    return value.trim()!==''&&Number.isFinite(n)&&Math.abs(n-q.answer)<=1e-3+roundoff;
  }
  return value===q.answer;
}
