import {validatePosition} from './position.js';
// Validate the complete content transaction before reading or writing learning records.
// Attack/terminal teaching fixtures may deliberately be invalid playable positions.
const object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v);
const assert=(condition,file,path,message)=>{if(!condition)throw Error(`${file} 内容不完整：${path} ${message}`);};
const text=(v,f,p)=>assert(typeof v==='string'&&v.trim().length>0&&v.length<=100000,f,p,'须为非空文本');
const list=(v,f,p,min=1)=>assert(Array.isArray(v)&&v.length>=min&&v.length<=1000,f,p,'须为有效列表');
const texts=(v,f,p,min=1)=>{list(v,f,p,min);v.forEach((s,i)=>text(s,f,p+'['+i+']'));};
function board(b,f,p){assert(Array.isArray(b)&&b.length===10,f,p,'须为10×9棋盘');for(let y=0;y<10;y++){assert((Array.isArray(b[y])||typeof b[y]==='string')&&b[y].length===9,f,p+'['+y+']','须有9格');for(let x=0;x<9;x++)assert(typeof b[y][x]==='string'&&b[y][x].length===1&&'.KAEHRCPkaehrcp'.includes(b[y][x]),f,p+'['+y+']['+x+']','棋子编码无效');}}
function lab(v,f,p,fixture=false){assert(object(v),f,p,'须为局面对象');board(v.board,f,p+'.board');assert(['red','black'].includes(fixture?v.sideToMove:v.side),f,p,'行动方须为red或black');if(!fixture){const checked=validatePosition(v.board,v.side);assert(checked.canSearch,f,p,'不能用于行棋实验：'+checked.errors.join(' '));}}
function tests(v,f,p){list(v,f,p);for(const [i,t]of v.entries()){const key=p+'['+i+']';assert(object(t),f,key,'须为测试对象');text(t.name,f,key+'.name');if(Object.hasOwn(t,'assert_code')){text(t.assert_code,f,key+'.assert_code');board(t.fixture_board,f,key+'.fixture_board');}else{list(t.args,f,key+'.args',0);assert(Object.hasOwn(t,'expected'),f,key+'.expected','缺少期望值');}}}
function exercise(e,f,p,transfer=false){assert(object(e),f,p,'须为练习对象');for(const key of ['id','title','function','signature','prompt','starter','solution'])text(e[key],f,p+'.'+key);assert(Number.isInteger(e.unit_id)&&e.unit_id>=1&&e.unit_id<=8,f,p+'.unit_id','须为1–8');texts(e.allowed_helpers,f,p+'.allowed_helpers',0);texts(e.forbidden_calls,f,p+'.forbidden_calls',0);assert(typeof e.mutates_board==='boolean',f,p+'.mutates_board','须为布尔值');tests(e.visible_tests,f,p+'.visible_tests');tests(e.hidden_tests,f,p+'.hidden_tests');lab(e.lab,f,p+'.lab');list(e.hints,f,p+'.hints');assert(e.hints.length===3,f,p+'.hints','须含3层提示');if(transfer){e.hints.forEach((h,i)=>text(h,f,p+'.hints['+i+']'));for(const key of ['knowledge','explain_prompt','basis'])text(e[key],f,p+'.'+key);text(e.lab.id,f,p+'.lab.id');text(e.lab.title,f,p+'.lab.title');if(e.syntax_example!==undefined)text(e.syntax_example,f,p+'.syntax_example');}else{for(const key of ['explanation','scaffold_note','transfer'])text(e[key],f,p+'.'+key);texts(e.concepts,f,p+'.concepts');e.hints.forEach((h,i)=>{assert(object(h)&&h.level===i+1,f,p+'.hints','提示层级须依次为1–3');text(h.text,f,p+'.hints['+i+'].text');});assert(object(e.solution_gate)&&e.solution_gate.default_open===false&&e.solution_gate.never_auto_reveal===true,f,p+'.solution_gate','参考解答须默认关闭');const q=e.prediction;assert(object(q),f,p+'.prediction','须为预测对象');text(q.question,f,p+'.prediction.question');text(q.explanation,f,p+'.prediction.explanation');texts(q.choices,f,p+'.prediction.choices');assert(q.choices.length>=2&&Number.isInteger(q.answer_index)&&q.answer_index>=0&&q.answer_index<q.choices.length,f,p+'.prediction.answer_index','预测选项索引无效');text(e.lab.objective,f,p+'.lab.objective');if(e.lab.presets!==undefined){list(e.lab.presets,f,p+'.lab.presets');for(const [i,pre]of e.lab.presets.entries()){lab(pre,f,p+'.lab.presets['+i+']');text(pre.id,f,p+'.lab.presets.id');text(pre.title,f,p+'.lab.presets.title');}}}}
export function validateContent(data){
 let f='curriculum.json';const c=data[f];assert(object(c),f,'root','须为对象');list(c.units,f,'units');assert(c.units.length===8,f,'units','须有8个单元');list(c.exercises,f,'exercises');assert(c.exercises.length===24,f,'exercises','须有24份核心练习');const units=c.units.map((u,i)=>{assert(object(u),f,'units['+i+']','须为对象');assert(Number.isInteger(u.id)&&u.id>=1&&u.id<=8,f,'units.id','须为1–8');for(const k of ['title','knowledge','prerequisite','goal'])text(u[k],f,'units['+i+'].'+k);texts(u.exercise_ids,f,'units.exercise_ids');return u;});assert(new Set(units.map(u=>u.id)).size===8,f,'units.id','单元不能重复');const ids=new Set();for(const [i,e]of c.exercises.entries()){exercise(e,f,'exercises['+i+']');assert(/^u0[1-8]e0[1-3]$/.test(e.id)&&Number(e.id.slice(1,3))===e.unit_id&&!ids.has(e.id),f,'exercises.id','固定ID无效或重复');ids.add(e.id);}for(const u of units){const expected=c.exercises.filter(e=>e.unit_id===u.id).map(e=>e.id).sort();assert(expected.length===3&&JSON.stringify([...u.exercise_ids].sort())===JSON.stringify(expected),f,'units.exercise_ids','单元与练习映射不一致');}
 f='transfers.json';const t=data[f];assert(object(t)&&t.version===1,f,'root','版本须为1');list(t.tasks,f,'tasks');assert(t.tasks.length===8,f,'tasks','须有8份独立迁移');const seen=new Set(),fixtureIds=new Set();for(const [i,e]of t.tasks.entries()){exercise(e,f,'tasks['+i+']',true);assert(e.id===`u0${e.unit_id}t01`&&!seen.has(e.unit_id),f,'tasks.id/unit_id','每单元须恰有一份迁移题');seen.add(e.unit_id);assert(!fixtureIds.has(e.lab.id)&&!['lesson','custom'].includes(e.lab.id),f,'tasks.lab.id','局面ID重复或保留');fixtureIds.add(e.lab.id);}
 f='lesson-activities.json';const a=data[f];assert(object(a),f,'root','须为对象');assert(Object.keys(a).length===24&&Object.keys(a).every(id=>ids.has(id)),f,'root','须对应全部24题');for(const id of ids){assert(object(a[id]),f,id,'缺少操作与解释');texts(a[id].steps,f,id+'.steps');for(const k of ['syntax','explain'])text(a[id][k],f,id+'.'+k);texts(a[id].checks,f,id+'.checks');if(a[id].syntax_example!==undefined)text(a[id].syntax_example,f,id+'.syntax_example');}
 f='positions.json';const p=data[f];assert(object(p),f,'root','须为对象');list(p.fixtures,f,'fixtures');assert(p.fixtures.length>=30,f,'fixtures','须有至少30份核验局面');for(const [i,v]of p.fixtures.entries()){lab(v,f,'fixtures['+i+']',true);for(const k of ['id','titleZh','purposeZh'])text(v[k],f,'fixtures['+i+'].'+k);assert(!fixtureIds.has(v.id)&&!['lesson','custom'].includes(v.id),f,'fixtures.id','局面ID重复或保留');fixtureIds.add(v.id);}for(const e of c.exercises)for(const v of e.lab.presets||[]){const id=e.id+'-'+v.id;assert(!fixtureIds.has(id),f,'presets.id','局面ID重复');fixtureIds.add(id);}assert(object(p.pieceCodes),f,'pieceCodes','须为棋子名称对象');for(const code of 'KAEHRCPkaehrcp')text(p.pieceCodes[code],f,'pieceCodes.'+code);list(p.sources,f,'sources');for(const v of p.sources){assert(object(v),f,'sources','须为来源对象');text(v.title,f,'sources.title');assert(typeof v.url==='string'&&/^https:\/\//.test(v.url),f,'sources.url','须为HTTPS来源链接');}
 return {curriculum:c,positions:p,transfers:t.tasks,activities:a,exercises:c.exercises,units};
}
export async function loadContent(fetcher=globalThis.fetch,timeoutMs=10000){
 const controller=new AbortController(),timers=setTimeout(()=>controller.abort(),timeoutMs);let failed=false;
 try{const names=['curriculum.json','positions.json','transfers.json','lesson-activities.json'];const entries=await Promise.all(names.map(async name=>{try{const response=await fetcher('./'+name,{signal:controller.signal,cache:'no-store'});if(!response.ok)throw Error(`${name} 请求失败（HTTP ${response.status}）`);let value;try{value=await response.json();}catch(error){if(controller.signal.aborted)throw Object.assign(Error(),{name:'AbortError'});throw Error(`${name} 不是有效JSON`);}return [name,value];}catch(error){if(failed)throw error;failed=true;controller.abort();if(error.name==='AbortError')throw Error(`${name} 加载超过10秒；请重新加载`);throw Error(error.message?.includes(name)?error.message:`${name} 无法读取；请重新加载`);}}));return validateContent(Object.fromEntries(entries));}finally{clearTimeout(timers);controller.abort();}
}
